---
title: "R Notebook"
output: html_notebook
---

```{r}
# testing different values of a, b and different steps on expected Ms
library(ggplot2)
library(LaplacesDemon)
source("./autoreg_testing.R")
```

```{r} 
# Testing a->1 with step size 40,000
start_time <- Sys.time()
a_s <- c(0.95, 0.995, 0.9995)
steps <- 40000
b <- 2
c <- 4
results <- c()
for(a in a_s) {
  results <- append(results, test_m(a, b, c, steps))
  print(sprintf("%f complete", a))
}
exp_ms <- 1 + 2*(a_s/(1-a_s))
to_plot <- data.frame(a_s, results, exp_ms)
end_time <- Sys.time()
print(end_time - start_time)
```
```{r}
ggplot(to_plot, aes(x=a_s)) + geom_point(aes(y=results, color="red"), size=0.75) + geom_line(aes(y=results,color="red")) + geom_line(aes(y=exp_ms, color="black")) + ggtitle("Comparing M to expected") + scale_color_manual(name = "", labels = c("Expected time", "Estimated time"),values = c("red", "black"))

```

```{r}
# Testing values of a with step size = 40 * t_exp
start_time <- Sys.time()
a_s <- c(-0.9, -0.75, -0.5, 0.25, 0.5, 0.75, 0.9)
b <- 2
c <- 4
results_40 <- c()
results_80 <- c()
for(a in a_s) {
  exp_m <- 1 + 2*(a/(1-a))
  steps_40 <- 40*exp_m
  results_40 <- append(results_40, test_m(a, b, c, steps_40))
  results_80 <- append(results_80, test_m(a,b,c, (2*steps_40)))
  print(sprintf("%f complete", a))
}
exp_ms <- 1 + 2*(a_s/(1-a_s))
to_plot <- data.frame(a_s, results_40, exp_ms, results_80)
end_time <- Sys.time()
print(end_time - start_time)
```

```{r}
ggplot(to_plot, aes(x=a_s)) + geom_point(aes(y=results_80, color="red"), size=0.75) + geom_line(aes(y=results_80,color="red"))+  geom_point(aes(y=results_40, color="blue"), size=0.75) + geom_line(aes(y=results_40,color="blue")) + geom_line(aes(y=exp_ms, color="black")) + ggtitle("Comparing M to expected") + scale_color_manual(name = "", labels = c("Expected time", "Estimated time(40t steps)", "Estimated time(80t steps)"),values = c("black", "blue", "red"))
# implement their algorithm
# save this data somehow
# run this multiple times, see what happens
write.csv(to_plot, "all_as.csv", row.names = FALSE)
```
```{r} 
# Testing a->-1 with step size 40,000
start_time <- Sys.time()
a_s <- c(-0.95, -0.995, -0.9995)
steps <- 40000
b <- 2
c <- 4
results <- c()
for(a in a_s) {
  results <- append(results, test_m(a, b, c, steps))
  print(sprintf("%f complete", a))
}
exp_ms <- 1 + 2*(a_s/(1-a_s))
to_plot <- data.frame(a_s, results, exp_ms)
end_time <- Sys.time()
print(end_time - start_time)
```
```{r}
ggplot(to_plot, aes(x=a_s)) + geom_point(aes(y=results, color="red"), size=0.75) + geom_line(aes(y=results,color="red")) + geom_line(aes(y=exp_ms, color="black")) + ggtitle("Comparing M to expected") + scale_color_manual(name = "", labels = c("Expected time", "Estimated time"),values = c("red", "black"))

```
