---
title: "Untitled"
author: "Bella Salter"
date: "2024-06-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
f <- function(x, t) {
  return(-1*x)
}

x0 <- 1
t <- 2
N <- 100
dt <- t/N
t <- seq(0, t, dt)

x <- rep(0, N+1)
x[1] <- x0

for(n in c(2:N+1)) {
  x[n] <- x[n-1] + dt * f(x[n-1], t[n-1])
}

x_exact <- exp(-1 * t)
to_plot <- data.frame(t, x_exact,x)
ggplot(to_plot, aes(x=t ) )+ geom_line(aes(y=x_exact)) + geom_point(aes(y=x), color="red")

E <- max(abs(x-x_exact))




```
```{r}
# SIR 
f <- function(x, t) {
  return(-1*x)
}

S0 <- 0.999
I0 <- 0.001
R0 <- 0
t <- 100
b <- 2
g <- 1

N <- 1000
dt <- t/N
t <- seq(0, t, dt)

S <- rep(0, N+1)
I <- rep(0, N+1)
R <- rep(0, N+1)
S[1] <- S0
I[1] <- I0
R[1] <- R0

for(n in c(2:N+1)) {
  S[n] <- S[n-1] + dt * (b/g * S[n-1] * I[n-1])
  I[n] <- I[n-1] + dt * (b*S[n-1]*I[n-1] - g*I[n-1])
  R[n] <- R[n-1] + dt * g * I[n-1]
}

x_exact <- exp(-1 * t)
to_plot <- data.frame(t, x_exact,x)
ggplot(to_plot, aes(x=t ) )+ geom_line(aes(y=x_exact)) + geom_point(aes(y=x), color="red")

E <- max(abs(x-x_exact))




```